# Revolut FAQ RAG Chatbot

A minimal single-turn RAG chatbot over Revolut help articles.

**Stack:** `openai` for embeddings + chat, `numpy` for similarity search, `json` for loading. No frameworks, no vector DB — everything in memory.

In [1]:
%pip install -q openai numpy

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:

    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz

    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with

    brew install pipx

    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.

    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.

    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
import asyncio
import os
from pathlib import Path
import numpy as np
import pandas as pd
from openai import OpenAI, AsyncOpenAI
from tqdm.asyncio import tqdm
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import config - single source of truth
import sys
sys.path.insert(0, str(Path(os.getcwd()).parent))
from src.config import *

print(f"Using EMBED_MODEL: {EMBED_MODEL}")
print(f"Using CHAT_MODEL: {CHAT_MODEL}")
print(f"Using TOP_K: {TOP_K}")

# Validate articles path exists
assert ARTICLES_PATH.exists(), f"Articles file not found: {ARTICLES_PATH}"
print(f"Articles path: {ARTICLES_PATH}")

# Initialize clients
client = OpenAI(api_key=OPENAI_API_KEY)
async_client = AsyncOpenAI(api_key=OPENAI_API_KEY)

# Load system prompt from file
with open(RAG_SYSTEM_PROMPT_PATH, 'r') as f:
    SYSTEM_PROMPT = f.read().strip()
print(f"Loaded system prompt from {RAG_SYSTEM_PROMPT_PATH}")

Using EMBED_MODEL: text-embedding-3-small
Using CHAT_MODEL: gpt-3.5-turbo
Using TOP_K: 4
Articles path: /Users/veniamin/Projects/chatbot-evals-ai/data/revolut_help_articles.jsonl
Loaded system prompt from /Users/veniamin/Projects/chatbot-evals-ai/prompts/rag_system.txt

## 1. Load articles

In [3]:
articles = []
with open(ARTICLES_PATH, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        articles.append(json.loads(line))

print(f"Loaded {len(articles)} articles from {ARTICLES_PATH}")
print("Example:", articles[0]["title"])

Loaded 786 articles from /Users/veniamin/Projects/chatbot-evals-ai/data/revolut_help_articles.jsonl
Example: How can I see my cashflow analytics?

## 2. Embed all articles

We embed `title + content_text` so the title contributes to retrieval. Batched to keep things fast.

In [4]:
def article_to_text(a):
    return f"{a['title']}\n\n{a['content_text']}"

def embed_texts(texts, batch_size=100):
    out = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        resp = client.embeddings.create(model=EMBED_MODEL, input=batch)
        out.extend([d.embedding for d in resp.data])
    return np.array(out, dtype=np.float32)

texts = [article_to_text(a) for a in articles]
embeddings = embed_texts(texts)

# L2-normalize once so cosine similarity is just a dot product
embeddings = embeddings / np.linalg.norm(embeddings, axis=1, keepdims=True)

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (786, 1536)

## 3. Retrieval

In [5]:
def retrieve(query, k=TOP_K):
    q_emb = client.embeddings.create(model=EMBED_MODEL, input=[query]).data[0].embedding
    q_vec = np.array(q_emb, dtype=np.float32)
    q_vec = q_vec / np.linalg.norm(q_vec)

    scores = embeddings @ q_vec
    top_idx = np.argsort(-scores)[:k]
    return [(int(i), float(scores[i]), articles[i]) for i in top_idx]

## 4. Single-turn chat

In [6]:
# SYSTEM_PROMPT is now loaded from prompts/rag_system.txt via config

def format_context(hits):
    parts = []
    for rank, (idx, score, art) in enumerate(hits, start=1):
        parts.append(
            f"[Article {rank}] {art['title']}\n{art['content_text']}"
        )
    return "\n\n---\n\n".join(parts)

def ask(question, k=TOP_K):
    """Sync ask function - thin wrapper over async_answer_with_context."""
    answer, context, hits = asyncio.run(async_answer_with_context(question, k=k))
    return answer, hits

async def async_answer_with_context(query, k=TOP_K):
    """
    Async RAG query that returns answer, extracted context, and hits.
    Uses AsyncOpenAI for both embedding and chat calls.
    """
    # Async embedding
    q_emb_resp = await async_client.embeddings.create(
        model=EMBED_MODEL,
        input=[query]
    )
    q_emb = q_emb_resp.data[0].embedding
    q_vec = np.array(q_emb, dtype=np.float32)
    q_vec = q_vec / np.linalg.norm(q_vec)
    
    # Retrieval
    scores = embeddings @ q_vec
    top_idx = np.argsort(-scores)[:k]
    hits = [(int(i), float(scores[i]), articles[i]) for i in top_idx]
    
    # Format context
    context = format_context(hits)
    
    # Async chat completion
    user_msg = (
        f"Help articles:\n\n{context}\n\n"
        f"Question: {query}"
    )
    
    resp = await async_client.chat.completions.create(
        model=CHAT_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_msg},
        ],
        temperature=0.2,
    )
    answer = resp.choices[0].message.content
    
    return answer, context, hits

## 5. Try it

In [7]:
question = "как открыть аккаунт в монзо"

# Test async_answer_with_context
answer, context, hits = await async_answer_with_context(question)

print("Q:", question)
print("\nA:", answer)
print("\nContext (first 200 chars):", context[:200] + "...")
print("\nRetrieved articles:")
for rank, (idx, score, art) in enumerate(hits, start=1):
    print(f"  {rank}. [{score:.3f}] {art['title']}")

Q: как открыть аккаунт в монзо

A: I don't know.

Context (first 200 chars): [Article 1] Open a Revolut – Kids & Teens account
## Create an account for your kids or teens
In the main Revolut app:
- Go to 'Home' on the bottom menu
- Below your balance, tap Accounts
- Tap 'Add ...

Retrieved articles:
  1. [0.369] Open a Revolut – Kids & Teens account
  2. [0.357] Duplicate account
  3. [0.337] Open an investment account
  4. [0.330] Change or verify email address

## 6. Evaluate Synthetic Dataset

Evaluate the RAG assistant on the synthetic dataset of 1500 queries.

In [8]:
# RAG evaluation settings
DATASET_PATH = DATA_DIR / "synthetic_revolut_queries.csv"
RAG_OUTPUT_PATH = DATA_DIR / "synthetic_revolut_rag_outputs.csv"
SAVE_EVERY = 25
RAG_CONCURRENCY = 8
MAX_EVAL_ROWS = None  # FULL DATASET - 1500 queries
ROW_KEY = ["persona", "scenario", "modifier", "query"]

# Load queries
df_queries = pd.read_csv(DATASET_PATH)
print(f"Loaded {len(df_queries)} synthetic queries")
df_queries.head()

Loaded 1500 synthetic queries

,persona,scenario,modifier,query
0,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,empty,I see an ATM withdrawal on my account that I d...
1,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,calm_at_home,A suspicious ATM withdrawal appeared today tha...
2,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,panic_security_fear,urgent! atm cash withdrawal just appeared on m...
3,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,angry_after_waiting,JUST SAW ATM withdrawal I DIDN'T MAKE! Need th...
4,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,confused_by_app_updates,There's an ATM withdrawal on my account that I...

In [9]:
import fcntl
import tempfile

def save_rows(df, path):
    """Atomic write: tmp + os.replace."""
    tmp_path = path.with_suffix('.tmp')
    df.to_csv(tmp_path, index=False)
    os.replace(tmp_path, path)

async def answer_dataset_row(row):
    """RAG answer for a single dataset row. Returns dict with exact 7 spec columns."""
    answer, context, hits = await async_answer_with_context(row["query"])
    return {
        "persona": row["persona"],
        "scenario": row["scenario"],
        "modifier": row["modifier"],
        "query": row["query"],
        "answer": answer,
        "extracted_context": context,  # Same format_context(hits) string sent to model
        "retrieved_articles": " | ".join([art["title"] for _, _, art in hits])
    }

async def run_rag_dataset(df_queries, output_path, row_key, max_eval_rows=None):
    """Run RAG evaluation with resume and checkpointing."""
    lock_path = DATA_DIR / ".rag_eval.lock"
    lock_fd = None
    
    # Single-writer lock
    try:
        lock_fd = open(lock_path, 'w')
        fcntl.flock(lock_fd.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        lock_fd.write(str(os.getpid()))
        lock_fd.flush()
    except (IOError, BlockingIOError):
        raise RuntimeError("RAG evaluation already running (lock held)")
    
    try:
        # Load existing output
        if output_path.exists():
            df_existing = pd.read_csv(output_path)
            # Dedupe by key, keep first complete
            df_existing = df_existing.drop_duplicates(subset=row_key, keep='first')
            done_keys = set(zip(*[df_existing[k] for k in row_key]))
            print(f"RAG resume: {len(done_keys)} done, {len(df_queries) - len(done_keys)} missing")
        else:
            df_existing = pd.DataFrame(columns=row_key + ["answer", "extracted_context", "retrieved_articles"])
            done_keys = set()
            print(f"RAG resume: 0 done, {len(df_queries)} missing")
        
        # Filter to missing rows
        df_todo = df_queries[
            ~df_queries.apply(lambda r: tuple(r[k] for k in row_key) in done_keys, axis=1)
        ]
        
        if max_eval_rows:
            df_todo = df_todo.head(max_eval_rows)
        
        if len(df_todo) == 0:
            print("No rows to process - all done")
            return df_existing
        
        print(f"Processing {len(df_todo)} queries...")
        
        # Process with concurrency control
        semaphore = asyncio.Semaphore(RAG_CONCURRENCY)
        results = []
        
        async def process_one(row):
            async with semaphore:
                return await answer_dataset_row(row)
        
        tasks = [process_one(row) for _, row in df_todo.iterrows()]
        
        for i, future in enumerate(tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="RAG")):
            result = await future
            results.append(result)
            
            # Checkpoint
            if (i + 1) % SAVE_EVERY == 0:
                df_checkpoint = pd.concat([df_existing, pd.DataFrame(results)], ignore_index=True)
                save_rows(df_checkpoint, output_path)
                print(f"Checkpoint: {i + 1}/{len(tasks)}")
        
        # Final save
        df_final = pd.concat([df_existing, pd.DataFrame(results)], ignore_index=True)
        save_rows(df_final, output_path)
        print(f"Saved {len(df_final)} results to {output_path}")
        
        return df_final
        
    finally:
        if lock_fd:
            fcntl.flock(lock_fd.fileno(), fcntl.LOCK_UN)
            lock_fd.close()
            if lock_path.exists():
                lock_path.unlink()

# Run evaluation
df_results = await run_rag_dataset(df_queries, RAG_OUTPUT_PATH, ROW_KEY, max_eval_rows=MAX_EVAL_ROWS)
print(f"Total results: {len(df_results)}")
df_results.head()

RAG resume: 25 done, 1475 missing
Processing 1475 queries...

RAG:   0%|          | 0/1475 [00:00<?, ?it/s]

RAG:   0%|          | 1/1475 [00:00<21:03,  1.17it/s]

RAG:   0%|          | 2/1475 [00:01<11:15,  2.18it/s]

RAG:   0%|          | 3/1475 [00:01<08:14,  2.98it/s]

RAG:   0%|          | 6/1475 [00:01<03:53,  6.30it/s]

RAG:   0%|          | 7/1475 [00:01<03:34,  6.85it/s]

RAG:   1%|          | 9/1475 [00:02<05:16,  4.63it/s]

RAG:   1%|          | 10/1475 [00:02<04:42,  5.18it/s]

RAG:   1%|          | 11/1475 [00:02<04:45,  5.12it/s]

RAG:   1%|          | 15/1475 [00:02<02:59,  8.12it/s]

RAG:   1%|          | 16/1475 [00:02<03:24,  7.14it/s]

RAG:   1%|          | 17/1475 [00:03<04:24,  5.51it/s]

RAG:   1%|▏         | 19/1475 [00:03<03:18,  7.34it/s]

RAG:   1%|▏         | 21/1475 [00:03<03:53,  6.22it/s]

RAG:   2%|▏         | 23/1475 [00:04<03:49,  6.32it/s]

RAG:   2%|▏         | 24/1475 [00:04<04:44,  5.11it/s]

RAG:   2%|▏         | 26/1475 [00:04<03:41,  6.55it/s]

RAG:   2%|▏         | 28/1475 [00:04<02:57,  8.16it/s]

Checkpoint: 25/1475

RAG:   2%|▏         | 30/1475 [00:04<02:40,  9.03it/s]

RAG:   2%|▏         | 32/1475 [00:05<03:26,  6.98it/s]

RAG:   2%|▏         | 33/1475 [00:05<04:22,  5.49it/s]

RAG:   3%|▎         | 37/1475 [00:06<03:20,  7.19it/s]

RAG:   3%|▎         | 38/1475 [00:06<03:16,  7.32it/s]

RAG:   3%|▎         | 39/1475 [00:06<03:43,  6.41it/s]

RAG:   3%|▎         | 40/1475 [00:06<03:46,  6.34it/s]

RAG:   3%|▎         | 41/1475 [00:06<04:21,  5.47it/s]

RAG:   3%|▎         | 42/1475 [00:07<03:53,  6.14it/s]

RAG:   3%|▎         | 45/1475 [00:07<02:21, 10.07it/s]

RAG:   3%|▎         | 47/1475 [00:07<04:10,  5.69it/s]

RAG:   3%|▎         | 48/1475 [00:08<04:21,  5.46it/s]

RAG:   3%|▎         | 50/1475 [00:08<03:16,  7.23it/s]

Checkpoint: 50/1475

RAG:   4%|▎         | 53/1475 [00:08<02:40,  8.84it/s]

RAG:   4%|▎         | 55/1475 [00:08<03:07,  7.57it/s]

RAG:   4%|▍         | 56/1475 [00:09<04:15,  5.54it/s]

RAG:   4%|▍         | 58/1475 [00:09<03:39,  6.47it/s]

RAG:   4%|▍         | 59/1475 [00:09<03:40,  6.43it/s]

RAG:   4%|▍         | 62/1475 [00:09<02:25,  9.74it/s]

RAG:   4%|▍         | 64/1475 [00:10<03:28,  6.77it/s]

RAG:   4%|▍         | 66/1475 [00:10<03:27,  6.81it/s]

RAG:   5%|▍         | 67/1475 [00:10<03:37,  6.48it/s]

RAG:   5%|▍         | 68/1475 [00:10<03:31,  6.64it/s]

RAG:   5%|▍         | 70/1475 [00:11<03:30,  6.68it/s]

RAG:   5%|▍         | 71/1475 [00:11<03:29,  6.69it/s]

RAG:   5%|▍         | 73/1475 [00:11<02:54,  8.02it/s]

RAG:   5%|▌         | 74/1475 [00:11<03:10,  7.34it/s]

RAG:   5%|▌         | 75/1475 [00:11<04:10,  5.59it/s]

RAG:   5%|▌         | 76/1475 [00:12<04:04,  5.73it/s]

Checkpoint: 75/1475

RAG:   5%|▌         | 77/1475 [00:12<04:06,  5.68it/s]

RAG:   5%|▌         | 79/1475 [00:12<02:56,  7.91it/s]

RAG:   5%|▌         | 81/1475 [00:12<03:13,  7.20it/s]

RAG:   6%|▌         | 82/1475 [00:13<04:49,  4.82it/s]

RAG:   6%|▌         | 83/1475 [00:13<04:46,  4.86it/s]

RAG:   6%|▌         | 87/1475 [00:13<02:59,  7.72it/s]

RAG:   6%|▌         | 88/1475 [00:13<03:15,  7.09it/s]

RAG:   6%|▌         | 90/1475 [00:14<03:33,  6.49it/s]

RAG:   6%|▌         | 92/1475 [00:14<02:55,  7.89it/s]

RAG:   6%|▋         | 93/1475 [00:14<02:51,  8.08it/s]

RAG:   6%|▋         | 94/1475 [00:14<03:29,  6.58it/s]

RAG:   6%|▋         | 95/1475 [00:14<04:21,  5.28it/s]

RAG:   7%|▋         | 97/1475 [00:15<03:21,  6.86it/s]

RAG:   7%|▋         | 99/1475 [00:15<03:16,  7.01it/s]

Checkpoint: 100/1475

RAG:   7%|▋         | 101/1475 [00:15<04:01,  5.70it/s]

RAG:   7%|▋         | 103/1475 [00:16<03:12,  7.14it/s]

RAG:   7%|▋         | 104/1475 [00:16<04:14,  5.39it/s]

RAG:   7%|▋         | 106/1475 [00:16<03:19,  6.86it/s]

RAG:   7%|▋         | 108/1475 [00:16<03:51,  5.91it/s]

RAG:   7%|▋         | 109/1475 [00:17<03:49,  5.96it/s]

RAG:   8%|▊         | 111/1475 [00:17<03:49,  5.96it/s]

RAG:   8%|▊         | 113/1475 [00:17<03:37,  6.25it/s]

RAG:   8%|▊         | 115/1475 [00:18<03:35,  6.32it/s]

RAG:   8%|▊         | 116/1475 [00:18<04:02,  5.60it/s]

RAG:   8%|▊         | 118/1475 [00:18<04:57,  4.56it/s]

RAG:   8%|▊         | 123/1475 [00:19<03:21,  6.70it/s]

RAG:   8%|▊         | 124/1475 [00:19<03:27,  6.50it/s]

RAG:   8%|▊         | 125/1475 [00:20<05:09,  4.36it/s]

Checkpoint: 125/1475

RAG:   9%|▊         | 129/1475 [00:20<03:21,  6.69it/s]

RAG:   9%|▉         | 131/1475 [00:20<03:03,  7.33it/s]

RAG:   9%|▉         | 133/1475 [00:20<02:46,  8.05it/s]

RAG:   9%|▉         | 134/1475 [00:21<04:02,  5.52it/s]

RAG:   9%|▉         | 136/1475 [00:21<03:15,  6.85it/s]

RAG:   9%|▉         | 137/1475 [00:21<03:05,  7.23it/s]

RAG:   9%|▉         | 139/1475 [00:21<02:51,  7.78it/s]

RAG:   9%|▉         | 140/1475 [00:21<03:06,  7.14it/s]

RAG:  10%|▉         | 142/1475 [00:22<04:13,  5.25it/s]

RAG:  10%|▉         | 146/1475 [00:22<02:26,  9.10it/s]

RAG:  10%|█         | 148/1475 [00:22<02:09, 10.22it/s]

RAG:  10%|█         | 150/1475 [00:23<03:57,  5.58it/s]

RAG:  10%|█         | 152/1475 [00:23<03:18,  6.67it/s]

Checkpoint: 150/1475

RAG:  10%|█         | 154/1475 [00:23<02:55,  7.51it/s]

RAG:  11%|█         | 157/1475 [00:24<02:15,  9.72it/s]

RAG:  11%|█         | 159/1475 [00:24<03:23,  6.48it/s]

RAG:  11%|█         | 161/1475 [00:24<02:59,  7.33it/s]

RAG:  11%|█         | 163/1475 [00:24<02:32,  8.62it/s]

RAG:  11%|█         | 165/1475 [00:25<02:22,  9.17it/s]

RAG:  11%|█▏        | 167/1475 [00:25<03:07,  6.98it/s]

RAG:  11%|█▏        | 168/1475 [00:25<03:23,  6.44it/s]

RAG:  12%|█▏        | 171/1475 [00:26<03:29,  6.24it/s]

RAG:  12%|█▏        | 173/1475 [00:26<03:20,  6.50it/s]

RAG:  12%|█▏        | 174/1475 [00:26<04:01,  5.38it/s]

RAG:  12%|█▏        | 176/1475 [00:27<03:36,  5.99it/s]

Checkpoint: 175/1475

RAG:  12%|█▏        | 180/1475 [00:27<02:11,  9.84it/s]

RAG:  12%|█▏        | 182/1475 [00:27<02:44,  7.88it/s]

RAG:  12%|█▏        | 184/1475 [00:28<03:42,  5.81it/s]

RAG:  13%|█▎        | 186/1475 [00:28<03:00,  7.12it/s]

RAG:  13%|█▎        | 188/1475 [00:28<03:07,  6.87it/s]

RAG:  13%|█▎        | 189/1475 [00:29<03:35,  5.97it/s]

RAG:  13%|█▎        | 191/1475 [00:29<03:44,  5.72it/s]

RAG:  13%|█▎        | 193/1475 [00:29<03:16,  6.51it/s]

RAG:  13%|█▎        | 196/1475 [00:29<02:49,  7.53it/s]

RAG:  13%|█▎        | 197/1475 [00:30<04:03,  5.24it/s]

RAG:  13%|█▎        | 198/1475 [00:30<04:32,  4.69it/s]

RAG:  14%|█▎        | 200/1475 [00:30<03:28,  6.10it/s]

RAG:  14%|█▎        | 202/1475 [00:31<03:01,  7.03it/s]

Checkpoint: 200/1475

RAG:  14%|█▍        | 204/1475 [00:31<02:49,  7.51it/s]

RAG:  14%|█▍        | 205/1475 [00:31<03:54,  5.42it/s]

RAG:  14%|█▍        | 206/1475 [00:31<03:47,  5.59it/s]

RAG:  14%|█▍        | 208/1475 [00:32<03:13,  6.54it/s]

RAG:  14%|█▍        | 210/1475 [00:32<03:13,  6.53it/s]

RAG:  14%|█▍        | 211/1475 [00:32<03:21,  6.28it/s]

RAG:  14%|█▍        | 212/1475 [00:32<03:27,  6.10it/s]

RAG:  14%|█▍        | 213/1475 [00:32<03:27,  6.09it/s]

RAG:  15%|█▍        | 215/1475 [00:33<02:28,  8.50it/s]

RAG:  15%|█▍        | 217/1475 [00:33<03:13,  6.50it/s]

RAG:  15%|█▍        | 219/1475 [00:33<02:39,  7.90it/s]

RAG:  15%|█▍        | 221/1475 [00:33<02:40,  7.82it/s]

RAG:  15%|█▌        | 222/1475 [00:34<03:11,  6.53it/s]

RAG:  15%|█▌        | 224/1475 [00:34<03:30,  5.95it/s]

RAG:  15%|█▌        | 225/1475 [00:34<03:42,  5.63it/s]

RAG:  15%|█▌        | 227/1475 [00:34<02:49,  7.37it/s]

Checkpoint: 225/1475

RAG:  16%|█▌        | 229/1475 [00:35<02:23,  8.69it/s]

RAG:  16%|█▌        | 231/1475 [00:35<04:28,  4.64it/s]

RAG:  16%|█▌        | 233/1475 [00:35<03:22,  6.12it/s]

RAG:  16%|█▌        | 237/1475 [00:36<02:09,  9.57it/s]

RAG:  16%|█▌        | 239/1475 [00:36<03:52,  5.32it/s]

RAG:  16%|█▋        | 242/1475 [00:37<03:10,  6.49it/s]

RAG:  17%|█▋        | 246/1475 [00:37<02:27,  8.36it/s]

RAG:  17%|█▋        | 248/1475 [00:38<03:13,  6.35it/s]

RAG:  17%|█▋        | 249/1475 [00:38<03:25,  5.97it/s]

RAG:  17%|█▋        | 253/1475 [00:38<02:13,  9.18it/s]

Checkpoint: 250/1475

RAG:  17%|█▋        | 255/1475 [00:38<02:56,  6.90it/s]

RAG:  17%|█▋        | 257/1475 [00:39<03:21,  6.04it/s]

RAG:  18%|█▊        | 259/1475 [00:39<03:23,  5.97it/s]

RAG:  18%|█▊        | 260/1475 [00:40<04:59,  4.05it/s]

RAG:  18%|█▊        | 262/1475 [00:40<03:56,  5.13it/s]

RAG:  18%|█▊        | 265/1475 [00:40<02:57,  6.82it/s]

RAG:  18%|█▊        | 266/1475 [00:41<03:40,  5.49it/s]

RAG:  18%|█▊        | 267/1475 [00:41<03:34,  5.62it/s]

RAG:  18%|█▊        | 268/1475 [00:41<03:17,  6.13it/s]

RAG:  18%|█▊        | 269/1475 [00:41<03:02,  6.61it/s]

RAG:  18%|█▊        | 270/1475 [00:41<02:53,  6.95it/s]

RAG:  18%|█▊        | 271/1475 [00:41<02:39,  7.55it/s]

RAG:  18%|█▊        | 272/1475 [00:41<02:46,  7.21it/s]

RAG:  19%|█▊        | 273/1475 [00:42<03:36,  5.56it/s]

RAG:  19%|█▊        | 275/1475 [00:42<02:58,  6.72it/s]

Checkpoint: 275/1475

RAG:  19%|█▉        | 277/1475 [00:42<02:41,  7.40it/s]

RAG:  19%|█▉        | 278/1475 [00:42<03:09,  6.30it/s]

RAG:  19%|█▉        | 280/1475 [00:43<02:21,  8.45it/s]

RAG:  19%|█▉        | 282/1475 [00:43<02:33,  7.79it/s]

RAG:  19%|█▉        | 283/1475 [00:43<03:27,  5.75it/s]

RAG:  19%|█▉        | 284/1475 [00:43<03:17,  6.04it/s]

RAG:  19%|█▉        | 285/1475 [00:43<03:02,  6.53it/s]

RAG:  19%|█▉        | 286/1475 [00:44<03:17,  6.03it/s]

RAG:  19%|█▉        | 287/1475 [00:44<03:01,  6.54it/s]

RAG:  20%|█▉        | 289/1475 [00:44<02:12,  8.95it/s]

RAG:  20%|█▉        | 291/1475 [00:45<03:55,  5.03it/s]

RAG:  20%|█▉        | 292/1475 [00:45<03:39,  5.39it/s]

RAG:  20%|█▉        | 294/1475 [00:45<02:52,  6.83it/s]

RAG:  20%|██        | 295/1475 [00:45<03:07,  6.28it/s]

RAG:  20%|██        | 297/1475 [00:45<02:21,  8.33it/s]

RAG:  20%|██        | 299/1475 [00:46<03:11,  6.13it/s]

RAG:  20%|██        | 300/1475 [00:46<03:24,  5.75it/s]

RAG:  20%|██        | 301/1475 [00:46<03:24,  5.73it/s]

Checkpoint: 300/1475

RAG:  21%|██        | 304/1475 [00:46<02:31,  7.75it/s]

RAG:  21%|██        | 307/1475 [00:47<02:49,  6.87it/s]

RAG:  21%|██        | 309/1475 [00:47<03:01,  6.44it/s]

RAG:  21%|██        | 311/1475 [00:47<02:59,  6.47it/s]

RAG:  21%|██        | 312/1475 [00:48<02:56,  6.61it/s]

RAG:  21%|██        | 313/1475 [00:48<02:54,  6.66it/s]

RAG:  21%|██▏       | 315/1475 [00:48<02:16,  8.52it/s]

RAG:  21%|██▏       | 317/1475 [00:48<02:44,  7.06it/s]

RAG:  22%|██▏       | 318/1475 [00:48<02:48,  6.86it/s]

RAG:  22%|██▏       | 320/1475 [00:49<02:47,  6.88it/s]

RAG:  22%|██▏       | 322/1475 [00:49<03:19,  5.77it/s]

RAG:  22%|██▏       | 324/1475 [00:49<02:43,  7.02it/s]

RAG:  22%|██▏       | 325/1475 [00:49<02:39,  7.23it/s]

RAG:  22%|██▏       | 326/1475 [00:50<02:42,  7.06it/s]

Checkpoint: 325/1475

RAG:  22%|██▏       | 327/1475 [00:50<02:32,  7.52it/s]

RAG:  22%|██▏       | 330/1475 [00:50<02:30,  7.62it/s]

RAG:  22%|██▏       | 331/1475 [00:50<02:31,  7.55it/s]

RAG:  23%|██▎       | 333/1475 [00:51<02:59,  6.37it/s]

RAG:  23%|██▎       | 334/1475 [00:51<02:58,  6.38it/s]

RAG:  23%|██▎       | 336/1475 [00:51<03:00,  6.32it/s]

RAG:  23%|██▎       | 338/1475 [00:51<02:46,  6.83it/s]

RAG:  23%|██▎       | 340/1475 [00:51<02:14,  8.41it/s]

RAG:  23%|██▎       | 341/1475 [00:52<02:33,  7.39it/s]

RAG:  23%|██▎       | 342/1475 [00:52<02:41,  7.03it/s]

RAG:  23%|██▎       | 343/1475 [00:52<03:21,  5.61it/s]

RAG:  23%|██▎       | 345/1475 [00:52<02:40,  7.05it/s]

RAG:  24%|██▎       | 347/1475 [00:52<02:02,  9.19it/s]

RAG:  24%|██▎       | 349/1475 [00:53<03:00,  6.23it/s]

RAG:  24%|██▎       | 350/1475 [00:53<03:06,  6.05it/s]

RAG:  24%|██▍       | 351/1475 [00:53<03:10,  5.89it/s]

Checkpoint: 350/1475

RAG:  24%|██▍       | 352/1475 [00:53<03:08,  5.95it/s]

RAG:  24%|██▍       | 353/1475 [00:54<04:10,  4.47it/s]

RAG:  24%|██▍       | 354/1475 [00:54<03:53,  4.80it/s]

RAG:  24%|██▍       | 355/1475 [00:54<03:31,  5.29it/s]

RAG:  24%|██▍       | 358/1475 [00:54<02:43,  6.82it/s]

RAG:  24%|██▍       | 359/1475 [00:55<02:53,  6.42it/s]

RAG:  24%|██▍       | 361/1475 [00:55<02:30,  7.38it/s]

RAG:  25%|██▍       | 362/1475 [00:55<02:43,  6.81it/s]

RAG:  25%|██▍       | 363/1475 [00:55<03:03,  6.05it/s]

RAG:  25%|██▍       | 365/1475 [00:56<03:05,  5.97it/s]

RAG:  25%|██▍       | 366/1475 [00:56<03:29,  5.30it/s]

RAG:  25%|██▍       | 368/1475 [00:56<02:33,  7.21it/s]

RAG:  25%|██▌       | 369/1475 [00:56<02:31,  7.29it/s]

RAG:  25%|██▌       | 371/1475 [00:56<02:31,  7.28it/s]

RAG:  25%|██▌       | 373/1475 [00:57<03:37,  5.07it/s]

RAG:  25%|██▌       | 375/1475 [00:57<03:14,  5.65it/s]

Checkpoint: 375/1475

RAG:  26%|██▌       | 379/1475 [00:58<02:08,  8.52it/s]

RAG:  26%|██▌       | 381/1475 [00:58<02:23,  7.61it/s]

RAG:  26%|██▌       | 382/1475 [00:58<03:04,  5.92it/s]

RAG:  26%|██▌       | 383/1475 [00:58<02:51,  6.36it/s]

RAG:  26%|██▋       | 388/1475 [00:59<01:32, 11.75it/s]

RAG:  26%|██▋       | 390/1475 [00:59<03:08,  5.76it/s]

RAG:  27%|██▋       | 393/1475 [01:00<02:33,  7.07it/s]

RAG:  27%|██▋       | 396/1475 [01:00<02:20,  7.69it/s]

RAG:  27%|██▋       | 398/1475 [01:00<02:14,  8.03it/s]

RAG:  27%|██▋       | 400/1475 [01:01<02:50,  6.29it/s]

Checkpoint: 400/1475

RAG:  27%|██▋       | 404/1475 [01:01<02:08,  8.32it/s]

RAG:  28%|██▊       | 406/1475 [01:01<02:01,  8.79it/s]

RAG:  28%|██▊       | 408/1475 [01:02<03:02,  5.84it/s]

RAG:  28%|██▊       | 409/1475 [01:02<02:53,  6.15it/s]

RAG:  28%|██▊       | 411/1475 [01:02<02:40,  6.62it/s]

RAG:  28%|██▊       | 412/1475 [01:02<02:41,  6.60it/s]

RAG:  28%|██▊       | 413/1475 [01:03<03:22,  5.25it/s]

RAG:  28%|██▊       | 415/1475 [01:03<02:51,  6.20it/s]

RAG:  28%|██▊       | 416/1475 [01:03<03:06,  5.69it/s]

RAG:  28%|██▊       | 418/1475 [01:03<02:44,  6.42it/s]

RAG:  28%|██▊       | 419/1475 [01:04<02:50,  6.18it/s]

RAG:  29%|██▊       | 421/1475 [01:04<02:47,  6.28it/s]

RAG:  29%|██▊       | 424/1475 [01:04<02:14,  7.83it/s]

RAG:  29%|██▉       | 425/1475 [01:04<02:48,  6.23it/s]

Checkpoint: 425/1475

RAG:  29%|██▉       | 427/1475 [01:05<02:31,  6.94it/s]

RAG:  29%|██▉       | 429/1475 [01:05<02:40,  6.51it/s]

RAG:  29%|██▉       | 431/1475 [01:05<02:36,  6.69it/s]

RAG:  29%|██▉       | 432/1475 [01:06<03:02,  5.73it/s]

RAG:  29%|██▉       | 434/1475 [01:06<02:38,  6.56it/s]

RAG:  30%|██▉       | 436/1475 [01:06<02:38,  6.55it/s]

RAG:  30%|██▉       | 438/1475 [01:06<02:31,  6.83it/s]

RAG:  30%|██▉       | 439/1475 [01:07<02:33,  6.75it/s]

RAG:  30%|██▉       | 441/1475 [01:07<02:09,  7.99it/s]

RAG:  30%|███       | 443/1475 [01:07<02:15,  7.62it/s]

RAG:  30%|███       | 444/1475 [01:07<02:11,  7.85it/s]

RAG:  30%|███       | 445/1475 [01:07<02:13,  7.72it/s]

RAG:  30%|███       | 446/1475 [01:07<02:12,  7.78it/s]

RAG:  30%|███       | 447/1475 [01:08<02:30,  6.82it/s]

RAG:  30%|███       | 449/1475 [01:08<01:49,  9.37it/s]

RAG:  31%|███       | 451/1475 [01:08<01:42, 10.03it/s]

RAG:  31%|███       | 453/1475 [01:08<01:37, 10.45it/s]

Checkpoint: 450/1475

RAG:  31%|███       | 455/1475 [01:09<02:27,  6.94it/s]

RAG:  31%|███       | 456/1475 [01:09<03:32,  4.80it/s]

RAG:  31%|███       | 460/1475 [01:09<01:59,  8.47it/s]

RAG:  31%|███▏      | 462/1475 [01:09<02:15,  7.47it/s]

RAG:  31%|███▏      | 464/1475 [01:10<02:30,  6.70it/s]

RAG:  32%|███▏      | 465/1475 [01:10<02:28,  6.81it/s]

RAG:  32%|███▏      | 467/1475 [01:11<03:05,  5.44it/s]

RAG:  32%|███▏      | 468/1475 [01:11<03:18,  5.08it/s]

RAG:  32%|███▏      | 469/1475 [01:11<02:58,  5.63it/s]

RAG:  32%|███▏      | 471/1475 [01:11<02:12,  7.55it/s]

RAG:  32%|███▏      | 473/1475 [01:11<02:18,  7.25it/s]

RAG:  32%|███▏      | 475/1475 [01:12<03:21,  4.96it/s]

Checkpoint: 475/1475

RAG:  32%|███▏      | 478/1475 [01:12<02:35,  6.42it/s]

RAG:  33%|███▎      | 480/1475 [01:12<02:18,  7.19it/s]

RAG:  33%|███▎      | 481/1475 [01:13<03:10,  5.22it/s]

RAG:  33%|███▎      | 482/1475 [01:13<03:11,  5.18it/s]

RAG:  33%|███▎      | 485/1475 [01:13<02:14,  7.33it/s]

RAG:  33%|███▎      | 486/1475 [01:13<02:23,  6.89it/s]

RAG:  33%|███▎      | 489/1475 [01:14<02:50,  5.78it/s]

RAG:  33%|███▎      | 490/1475 [01:14<03:17,  4.99it/s]

RAG:  33%|███▎      | 493/1475 [01:15<02:38,  6.21it/s]

RAG:  34%|███▎      | 496/1475 [01:15<02:02,  8.02it/s]

RAG:  34%|███▎      | 497/1475 [01:16<03:17,  4.94it/s]

RAG:  34%|███▍      | 498/1475 [01:16<03:14,  5.02it/s]

RAG:  34%|███▍      | 500/1475 [01:16<02:55,  5.57it/s]

RAG:  34%|███▍      | 503/1475 [01:16<02:03,  7.88it/s]

Checkpoint: 500/1475

RAG:  34%|███▍      | 505/1475 [01:17<02:50,  5.68it/s]

RAG:  34%|███▍      | 506/1475 [01:17<02:45,  5.85it/s]

RAG:  34%|███▍      | 507/1475 [01:17<02:47,  5.78it/s]

RAG:  34%|███▍      | 508/1475 [01:17<02:40,  6.01it/s]

RAG:  35%|███▍      | 509/1475 [01:18<03:13,  4.99it/s]

RAG:  35%|███▍      | 513/1475 [01:18<01:44,  9.24it/s]

RAG:  35%|███▍      | 515/1475 [01:18<02:10,  7.36it/s]

RAG:  35%|███▍      | 516/1475 [01:18<02:09,  7.40it/s]

RAG:  35%|███▌      | 517/1475 [01:18<02:07,  7.49it/s]

RAG:  35%|███▌      | 519/1475 [01:19<02:13,  7.17it/s]

RAG:  35%|███▌      | 520/1475 [01:19<02:12,  7.21it/s]

RAG:  35%|███▌      | 521/1475 [01:19<03:02,  5.22it/s]

RAG:  35%|███▌      | 522/1475 [01:19<02:46,  5.74it/s]

RAG:  36%|███▌      | 524/1475 [01:20<02:10,  7.26it/s]

RAG:  36%|███▌      | 525/1475 [01:20<02:08,  7.40it/s]

Checkpoint: 525/1475

RAG:  36%|███▌      | 527/1475 [01:20<02:25,  6.53it/s]

RAG:  36%|███▌      | 528/1475 [01:20<02:40,  5.90it/s]

RAG:  36%|███▌      | 530/1475 [01:20<02:22,  6.61it/s]

RAG:  36%|███▌      | 531/1475 [01:21<02:26,  6.44it/s]

RAG:  36%|███▌      | 532/1475 [01:21<02:17,  6.88it/s]

RAG:  36%|███▋      | 535/1475 [01:21<01:32, 10.19it/s]

RAG:  36%|███▋      | 537/1475 [01:22<02:35,  6.04it/s]

RAG:  36%|███▋      | 538/1475 [01:22<02:32,  6.14it/s]

RAG:  37%|███▋      | 540/1475 [01:22<02:00,  7.79it/s]

RAG:  37%|███▋      | 542/1475 [01:22<02:06,  7.40it/s]

RAG:  37%|███▋      | 543/1475 [01:22<02:21,  6.57it/s]

RAG:  37%|███▋      | 544/1475 [01:23<03:01,  5.12it/s]

RAG:  37%|███▋      | 545/1475 [01:23<03:17,  4.72it/s]

RAG:  37%|███▋      | 546/1475 [01:23<02:51,  5.42it/s]

RAG:  37%|███▋      | 547/1475 [01:23<02:39,  5.82it/s]

RAG:  37%|███▋      | 549/1475 [01:23<02:15,  6.85it/s]

RAG:  37%|███▋      | 550/1475 [01:24<02:07,  7.24it/s]

Checkpoint: 550/1475

RAG:  37%|███▋      | 552/1475 [01:24<02:01,  7.58it/s]

RAG:  38%|███▊      | 554/1475 [01:24<02:30,  6.11it/s]

RAG:  38%|███▊      | 555/1475 [01:24<02:29,  6.15it/s]

RAG:  38%|███▊      | 558/1475 [01:24<01:35,  9.63it/s]

RAG:  38%|███▊      | 560/1475 [01:25<02:27,  6.20it/s]

RAG:  38%|███▊      | 562/1475 [01:25<02:13,  6.83it/s]

RAG:  38%|███▊      | 564/1475 [01:26<02:11,  6.91it/s]

RAG:  38%|███▊      | 566/1475 [01:26<01:52,  8.05it/s]

RAG:  39%|███▊      | 568/1475 [01:26<02:43,  5.56it/s]

RAG:  39%|███▊      | 571/1475 [01:27<02:24,  6.25it/s]

RAG:  39%|███▉      | 572/1475 [01:27<02:21,  6.37it/s]

RAG:  39%|███▉      | 574/1475 [01:27<02:18,  6.50it/s]

RAG:  39%|███▉      | 575/1475 [01:27<02:28,  6.04it/s]

Checkpoint: 575/1475

RAG:  39%|███▉      | 576/1475 [01:28<02:35,  5.78it/s]

RAG:  39%|███▉      | 577/1475 [01:28<02:39,  5.64it/s]

RAG:  39%|███▉      | 579/1475 [01:28<03:07,  4.78it/s]

RAG:  39%|███▉      | 581/1475 [01:28<02:31,  5.92it/s]

RAG:  40%|███▉      | 584/1475 [01:29<02:45,  5.38it/s]

RAG:  40%|███▉      | 586/1475 [01:29<02:29,  5.96it/s]

RAG:  40%|███▉      | 587/1475 [01:30<02:28,  5.99it/s]

RAG:  40%|████      | 591/1475 [01:30<02:02,  7.20it/s]

RAG:  40%|████      | 592/1475 [01:30<02:00,  7.30it/s]

RAG:  40%|████      | 593/1475 [01:30<01:55,  7.65it/s]

RAG:  40%|████      | 595/1475 [01:30<01:59,  7.37it/s]

RAG:  40%|████      | 596/1475 [01:31<02:14,  6.53it/s]

RAG:  40%|████      | 597/1475 [01:31<02:14,  6.53it/s]

RAG:  41%|████      | 598/1475 [01:31<02:47,  5.23it/s]

RAG:  41%|████      | 600/1475 [01:32<02:41,  5.43it/s]

RAG:  41%|████      | 603/1475 [01:32<01:39,  8.73it/s]

Checkpoint: 600/1475

RAG:  41%|████      | 605/1475 [01:32<02:29,  5.83it/s]

RAG:  41%|████      | 607/1475 [01:32<02:15,  6.38it/s]

RAG:  41%|████      | 608/1475 [01:33<02:31,  5.74it/s]

RAG:  41%|████▏     | 610/1475 [01:33<01:57,  7.39it/s]

RAG:  41%|████▏     | 612/1475 [01:33<02:08,  6.71it/s]

RAG:  42%|████▏     | 613/1475 [01:33<02:06,  6.83it/s]

RAG:  42%|████▏     | 615/1475 [01:33<01:45,  8.16it/s]

RAG:  42%|████▏     | 616/1475 [01:34<02:26,  5.85it/s]

RAG:  42%|████▏     | 618/1475 [01:34<01:48,  7.87it/s]

RAG:  42%|████▏     | 620/1475 [01:34<01:56,  7.35it/s]

RAG:  42%|████▏     | 621/1475 [01:34<02:02,  6.95it/s]

RAG:  42%|████▏     | 622/1475 [01:35<02:23,  5.94it/s]

RAG:  42%|████▏     | 623/1475 [01:35<02:56,  4.83it/s]

RAG:  42%|████▏     | 625/1475 [01:35<02:27,  5.77it/s]

RAG:  42%|████▏     | 626/1475 [01:35<02:17,  6.19it/s]

Checkpoint: 625/1475

RAG:  43%|████▎     | 627/1475 [01:36<03:19,  4.25it/s]

RAG:  43%|████▎     | 629/1475 [01:36<02:18,  6.10it/s]

RAG:  43%|████▎     | 631/1475 [01:36<01:58,  7.10it/s]

RAG:  43%|████▎     | 632/1475 [01:36<01:56,  7.24it/s]

RAG:  43%|████▎     | 634/1475 [01:37<02:32,  5.51it/s]

RAG:  43%|████▎     | 635/1475 [01:37<02:26,  5.74it/s]

RAG:  43%|████▎     | 637/1475 [01:37<02:20,  5.97it/s]

RAG:  43%|████▎     | 638/1475 [01:37<02:22,  5.86it/s]

RAG:  43%|████▎     | 639/1475 [01:38<02:09,  6.45it/s]

RAG:  43%|████▎     | 640/1475 [01:38<02:00,  6.92it/s]

RAG:  44%|████▎     | 642/1475 [01:38<02:03,  6.75it/s]

RAG:  44%|████▎     | 644/1475 [01:38<02:18,  5.99it/s]

RAG:  44%|████▎     | 645/1475 [01:39<02:12,  6.24it/s]

RAG:  44%|████▍     | 648/1475 [01:39<01:57,  7.06it/s]

RAG:  44%|████▍     | 649/1475 [01:39<01:56,  7.11it/s]

RAG:  44%|████▍     | 650/1475 [01:39<02:01,  6.77it/s]

Checkpoint: 650/1475

RAG:  44%|████▍     | 652/1475 [01:39<01:53,  7.24it/s]

RAG:  44%|████▍     | 653/1475 [01:40<01:47,  7.68it/s]

RAG:  44%|████▍     | 654/1475 [01:40<01:59,  6.87it/s]

RAG:  44%|████▍     | 655/1475 [01:40<02:02,  6.68it/s]

RAG:  44%|████▍     | 656/1475 [01:40<02:20,  5.85it/s]

RAG:  45%|████▍     | 657/1475 [01:40<02:21,  5.79it/s]

RAG:  45%|████▍     | 660/1475 [01:41<01:47,  7.61it/s]

RAG:  45%|████▍     | 662/1475 [01:41<01:59,  6.83it/s]

RAG:  45%|████▍     | 663/1475 [01:41<02:04,  6.55it/s]

RAG:  45%|████▌     | 664/1475 [01:42<02:50,  4.77it/s]

RAG:  45%|████▌     | 667/1475 [01:42<01:54,  7.08it/s]

RAG:  45%|████▌     | 669/1475 [01:42<01:45,  7.65it/s]

RAG:  45%|████▌     | 670/1475 [01:43<03:06,  4.32it/s]

RAG:  45%|████▌     | 671/1475 [01:43<02:46,  4.83it/s]

RAG:  46%|████▌     | 674/1475 [01:43<01:55,  6.95it/s]

Checkpoint: 675/1475

RAG:  46%|████▌     | 676/1475 [01:44<02:36,  5.11it/s]

RAG:  46%|████▌     | 678/1475 [01:44<02:24,  5.50it/s]

RAG:  46%|████▌     | 679/1475 [01:44<02:16,  5.83it/s]

RAG:  46%|████▌     | 680/1475 [01:44<02:12,  5.99it/s]

RAG:  46%|████▋     | 683/1475 [01:45<02:16,  5.82it/s]

RAG:  46%|████▋     | 684/1475 [01:45<02:12,  5.98it/s]

RAG:  47%|████▋     | 686/1475 [01:45<02:09,  6.08it/s]

RAG:  47%|████▋     | 687/1475 [01:45<02:05,  6.27it/s]

RAG:  47%|████▋     | 689/1475 [01:46<02:42,  4.83it/s]

RAG:  47%|████▋     | 691/1475 [01:46<02:32,  5.15it/s]

RAG:  47%|████▋     | 694/1475 [01:46<01:41,  7.67it/s]

RAG:  47%|████▋     | 696/1475 [01:47<02:34,  5.05it/s]

RAG:  47%|████▋     | 698/1475 [01:47<02:24,  5.36it/s]

RAG:  48%|████▊     | 701/1475 [01:48<01:41,  7.61it/s]

Checkpoint: 700/1475

RAG:  48%|████▊     | 703/1475 [01:48<02:04,  6.20it/s]

RAG:  48%|████▊     | 705/1475 [01:48<02:14,  5.71it/s]

RAG:  48%|████▊     | 706/1475 [01:49<02:19,  5.50it/s]

RAG:  48%|████▊     | 708/1475 [01:49<02:00,  6.37it/s]

RAG:  48%|████▊     | 709/1475 [01:49<02:08,  5.97it/s]

RAG:  48%|████▊     | 710/1475 [01:49<02:02,  6.26it/s]

RAG:  48%|████▊     | 712/1475 [01:50<02:19,  5.46it/s]

RAG:  48%|████▊     | 714/1475 [01:50<01:46,  7.17it/s]

RAG:  48%|████▊     | 715/1475 [01:50<01:50,  6.86it/s]

RAG:  49%|████▊     | 717/1475 [01:51<02:29,  5.06it/s]

RAG:  49%|████▉     | 721/1475 [01:51<01:49,  6.91it/s]

RAG:  49%|████▉     | 722/1475 [01:51<01:55,  6.52it/s]

RAG:  49%|████▉     | 725/1475 [01:52<01:56,  6.44it/s]

RAG:  49%|████▉     | 727/1475 [01:52<01:35,  7.84it/s]

Checkpoint: 725/1475

RAG:  49%|████▉     | 729/1475 [01:52<01:58,  6.30it/s]

RAG:  49%|████▉     | 730/1475 [01:52<01:57,  6.35it/s]

RAG:  50%|████▉     | 733/1475 [01:53<01:34,  7.89it/s]

RAG:  50%|████▉     | 734/1475 [01:53<01:35,  7.73it/s]

RAG:  50%|████▉     | 736/1475 [01:54<02:50,  4.33it/s]

RAG:  50%|█████     | 738/1475 [01:54<02:17,  5.38it/s]

RAG:  50%|█████     | 740/1475 [01:54<01:48,  6.75it/s]

RAG:  50%|█████     | 742/1475 [01:54<01:34,  7.77it/s]

RAG:  50%|█████     | 744/1475 [01:55<02:06,  5.77it/s]

RAG:  51%|█████     | 745/1475 [01:55<02:22,  5.14it/s]

RAG:  51%|█████     | 748/1475 [01:55<01:38,  7.35it/s]

RAG:  51%|█████     | 750/1475 [01:55<01:25,  8.49it/s]

Checkpoint: 750/1475

RAG:  51%|█████     | 752/1475 [01:56<01:56,  6.18it/s]

RAG:  51%|█████     | 753/1475 [01:56<02:03,  5.83it/s]

RAG:  51%|█████     | 754/1475 [01:56<01:54,  6.28it/s]

RAG:  51%|█████▏    | 756/1475 [01:56<01:27,  8.26it/s]

RAG:  51%|█████▏    | 758/1475 [01:56<01:12,  9.94it/s]

RAG:  52%|█████▏    | 760/1475 [01:57<02:05,  5.68it/s]

RAG:  52%|█████▏    | 763/1475 [01:57<01:30,  7.88it/s]

RAG:  52%|█████▏    | 765/1475 [01:57<01:15,  9.46it/s]

RAG:  52%|█████▏    | 767/1475 [01:58<02:28,  4.77it/s]

RAG:  52%|█████▏    | 769/1475 [01:59<02:34,  4.58it/s]

RAG:  52%|█████▏    | 772/1475 [01:59<01:58,  5.92it/s]

RAG:  52%|█████▏    | 774/1475 [01:59<02:06,  5.56it/s]

RAG:  53%|█████▎    | 775/1475 [02:00<02:39,  4.39it/s]

RAG:  53%|█████▎    | 776/1475 [02:00<02:23,  4.88it/s]

Checkpoint: 775/1475

RAG:  53%|█████▎    | 779/1475 [02:00<01:36,  7.21it/s]

RAG:  53%|█████▎    | 781/1475 [02:01<02:12,  5.24it/s]

RAG:  53%|█████▎    | 783/1475 [02:01<01:59,  5.77it/s]

RAG:  53%|█████▎    | 785/1475 [02:01<01:41,  6.81it/s]

RAG:  53%|█████▎    | 786/1475 [02:01<01:46,  6.47it/s]

RAG:  53%|█████▎    | 788/1475 [02:02<01:44,  6.60it/s]

RAG:  54%|█████▎    | 791/1475 [02:02<01:16,  8.91it/s]

RAG:  54%|█████▍    | 793/1475 [02:03<02:19,  4.89it/s]

RAG:  54%|█████▍    | 795/1475 [02:03<01:52,  6.02it/s]

RAG:  54%|█████▍    | 797/1475 [02:03<01:32,  7.34it/s]

RAG:  54%|█████▍    | 799/1475 [02:03<01:15,  9.01it/s]

RAG:  54%|█████▍    | 801/1475 [02:04<02:01,  5.54it/s]

Checkpoint: 800/1475

RAG:  55%|█████▍    | 804/1475 [02:04<01:24,  7.94it/s]

RAG:  55%|█████▍    | 806/1475 [02:04<01:34,  7.07it/s]

RAG:  55%|█████▍    | 808/1475 [02:05<01:44,  6.37it/s]

RAG:  55%|█████▍    | 810/1475 [02:05<01:50,  6.04it/s]

RAG:  55%|█████▌    | 812/1475 [02:05<01:31,  7.25it/s]

RAG:  55%|█████▌    | 814/1475 [02:05<01:18,  8.46it/s]

RAG:  55%|█████▌    | 816/1475 [02:06<01:31,  7.22it/s]

RAG:  55%|█████▌    | 817/1475 [02:06<01:49,  5.99it/s]

RAG:  56%|█████▌    | 820/1475 [02:06<01:15,  8.70it/s]

RAG:  56%|█████▌    | 822/1475 [02:06<01:21,  7.98it/s]

RAG:  56%|█████▌    | 824/1475 [02:07<01:27,  7.41it/s]

RAG:  56%|█████▌    | 825/1475 [02:07<02:05,  5.18it/s]

Checkpoint: 825/1475

RAG:  56%|█████▌    | 829/1475 [02:08<01:29,  7.20it/s]

RAG:  56%|█████▋    | 831/1475 [02:08<01:54,  5.63it/s]

RAG:  56%|█████▋    | 832/1475 [02:08<01:47,  5.98it/s]

RAG:  57%|█████▋    | 836/1475 [02:08<01:11,  8.96it/s]

RAG:  57%|█████▋    | 838/1475 [02:09<01:17,  8.23it/s]

RAG:  57%|█████▋    | 839/1475 [02:09<01:45,  6.05it/s]

RAG:  57%|█████▋    | 840/1475 [02:10<02:10,  4.86it/s]

RAG:  57%|█████▋    | 843/1475 [02:10<01:26,  7.33it/s]

RAG:  57%|█████▋    | 845/1475 [02:10<01:34,  6.70it/s]

RAG:  57%|█████▋    | 846/1475 [02:10<01:29,  6.99it/s]

RAG:  57%|█████▋    | 848/1475 [02:11<01:44,  5.99it/s]

RAG:  58%|█████▊    | 850/1475 [02:11<01:44,  6.01it/s]

RAG:  58%|█████▊    | 851/1475 [02:11<01:47,  5.78it/s]

Checkpoint: 850/1475

RAG:  58%|█████▊    | 852/1475 [02:11<01:42,  6.09it/s]

RAG:  58%|█████▊    | 854/1475 [02:11<01:29,  6.92it/s]

RAG:  58%|█████▊    | 855/1475 [02:12<01:39,  6.21it/s]

RAG:  58%|█████▊    | 857/1475 [02:12<01:48,  5.71it/s]

RAG:  58%|█████▊    | 858/1475 [02:12<01:55,  5.35it/s]

RAG:  58%|█████▊    | 861/1475 [02:13<01:25,  7.22it/s]

RAG:  58%|█████▊    | 862/1475 [02:13<01:22,  7.44it/s]

RAG:  59%|█████▊    | 863/1475 [02:13<01:32,  6.60it/s]

RAG:  59%|█████▊    | 866/1475 [02:13<01:08,  8.86it/s]

RAG:  59%|█████▉    | 867/1475 [02:13<01:38,  6.18it/s]

RAG:  59%|█████▉    | 869/1475 [02:14<01:39,  6.10it/s]

RAG:  59%|█████▉    | 871/1475 [02:14<01:27,  6.90it/s]

RAG:  59%|█████▉    | 873/1475 [02:14<01:11,  8.44it/s]

RAG:  59%|█████▉    | 875/1475 [02:15<01:29,  6.68it/s]

Checkpoint: 875/1475

RAG:  59%|█████▉    | 877/1475 [02:15<01:26,  6.94it/s]

RAG:  60%|█████▉    | 878/1475 [02:15<01:24,  7.06it/s]

RAG:  60%|█████▉    | 879/1475 [02:15<01:25,  6.98it/s]

RAG:  60%|█████▉    | 881/1475 [02:15<01:06,  8.92it/s]

RAG:  60%|█████▉    | 883/1475 [02:16<01:23,  7.13it/s]

RAG:  60%|██████    | 885/1475 [02:16<01:05,  8.99it/s]

RAG:  60%|██████    | 887/1475 [02:16<01:01,  9.50it/s]

RAG:  60%|██████    | 889/1475 [02:16<01:26,  6.79it/s]

RAG:  60%|██████    | 890/1475 [02:17<01:48,  5.39it/s]

RAG:  60%|██████    | 891/1475 [02:17<01:40,  5.83it/s]

RAG:  60%|██████    | 892/1475 [02:17<01:43,  5.62it/s]

RAG:  61%|██████    | 893/1475 [02:17<01:36,  6.02it/s]

RAG:  61%|██████    | 898/1475 [02:18<01:39,  5.81it/s]

RAG:  61%|██████    | 899/1475 [02:18<01:37,  5.90it/s]

RAG:  61%|██████    | 900/1475 [02:18<01:31,  6.27it/s]

Checkpoint: 900/1475

RAG:  61%|██████▏   | 904/1475 [02:19<01:04,  8.79it/s]

RAG:  61%|██████▏   | 906/1475 [02:19<01:29,  6.36it/s]

RAG:  61%|██████▏   | 907/1475 [02:19<01:37,  5.84it/s]

RAG:  62%|██████▏   | 910/1475 [02:20<01:15,  7.46it/s]

RAG:  62%|██████▏   | 911/1475 [02:20<01:24,  6.64it/s]

RAG:  62%|██████▏   | 912/1475 [02:20<01:24,  6.67it/s]

RAG:  62%|██████▏   | 914/1475 [02:20<01:18,  7.17it/s]

RAG:  62%|██████▏   | 915/1475 [02:21<01:35,  5.88it/s]

RAG:  62%|██████▏   | 916/1475 [02:21<01:37,  5.74it/s]

RAG:  62%|██████▏   | 918/1475 [02:21<01:21,  6.80it/s]

RAG:  62%|██████▏   | 920/1475 [02:21<01:08,  8.08it/s]

RAG:  62%|██████▏   | 921/1475 [02:21<01:17,  7.18it/s]

RAG:  63%|██████▎   | 922/1475 [02:22<01:39,  5.55it/s]

RAG:  63%|██████▎   | 923/1475 [02:22<01:30,  6.11it/s]

RAG:  63%|██████▎   | 924/1475 [02:22<01:33,  5.92it/s]

RAG:  63%|██████▎   | 925/1475 [02:22<01:55,  4.78it/s]

RAG:  63%|██████▎   | 927/1475 [02:22<01:20,  6.80it/s]

Checkpoint: 925/1475

RAG:  63%|██████▎   | 928/1475 [02:23<01:29,  6.08it/s]

RAG:  63%|██████▎   | 930/1475 [02:23<01:22,  6.62it/s]

RAG:  63%|██████▎   | 931/1475 [02:23<01:35,  5.70it/s]

RAG:  63%|██████▎   | 933/1475 [02:24<01:38,  5.53it/s]

RAG:  63%|██████▎   | 934/1475 [02:24<01:35,  5.64it/s]

RAG:  63%|██████▎   | 936/1475 [02:24<01:27,  6.13it/s]

RAG:  64%|██████▎   | 938/1475 [02:24<01:15,  7.07it/s]

RAG:  64%|██████▎   | 939/1475 [02:24<01:34,  5.66it/s]

RAG:  64%|██████▍   | 941/1475 [02:25<01:19,  6.75it/s]

RAG:  64%|██████▍   | 942/1475 [02:25<02:23,  3.71it/s]

RAG:  64%|██████▍   | 946/1475 [02:26<01:16,  6.93it/s]

RAG:  64%|██████▍   | 948/1475 [02:26<01:23,  6.28it/s]

RAG:  64%|██████▍   | 949/1475 [02:26<01:54,  4.60it/s]

RAG:  64%|██████▍   | 950/1475 [02:27<02:08,  4.08it/s]

RAG:  65%|██████▍   | 954/1475 [02:27<01:11,  7.28it/s]

Checkpoint: 950/1475

RAG:  65%|██████▍   | 956/1475 [02:27<01:21,  6.35it/s]

RAG:  65%|██████▍   | 957/1475 [02:28<01:28,  5.86it/s]

RAG:  65%|██████▍   | 958/1475 [02:28<01:28,  5.87it/s]

RAG:  65%|██████▌   | 960/1475 [02:28<01:06,  7.79it/s]

RAG:  65%|██████▌   | 962/1475 [02:28<01:06,  7.68it/s]

RAG:  65%|██████▌   | 964/1475 [02:28<01:03,  8.02it/s]

RAG:  65%|██████▌   | 965/1475 [02:29<01:15,  6.75it/s]

RAG:  65%|██████▌   | 966/1475 [02:29<01:19,  6.38it/s]

RAG:  66%|██████▌   | 968/1475 [02:29<01:04,  7.91it/s]

RAG:  66%|██████▌   | 969/1475 [02:29<01:05,  7.74it/s]

RAG:  66%|██████▌   | 970/1475 [02:29<01:25,  5.90it/s]

RAG:  66%|██████▌   | 971/1475 [02:30<01:51,  4.54it/s]

RAG:  66%|██████▌   | 974/1475 [02:30<01:06,  7.51it/s]

RAG:  66%|██████▌   | 976/1475 [02:30<00:52,  9.45it/s]

Checkpoint: 975/1475

RAG:  66%|██████▋   | 978/1475 [02:31<01:23,  5.97it/s]

RAG:  66%|██████▋   | 980/1475 [02:31<01:15,  6.59it/s]

RAG:  67%|██████▋   | 982/1475 [02:31<01:17,  6.40it/s]

RAG:  67%|██████▋   | 985/1475 [02:31<00:56,  8.73it/s]

RAG:  67%|██████▋   | 987/1475 [02:32<01:20,  6.02it/s]

RAG:  67%|██████▋   | 988/1475 [02:32<01:16,  6.39it/s]

RAG:  67%|██████▋   | 989/1475 [02:32<01:26,  5.63it/s]

RAG:  67%|██████▋   | 990/1475 [02:33<01:20,  6.04it/s]

RAG:  67%|██████▋   | 991/1475 [02:33<01:45,  4.57it/s]

RAG:  67%|██████▋   | 992/1475 [02:33<01:48,  4.45it/s]

RAG:  67%|██████▋   | 993/1475 [02:33<02:04,  3.88it/s]

RAG:  67%|██████▋   | 995/1475 [02:34<01:24,  5.67it/s]

RAG:  68%|██████▊   | 997/1475 [02:34<01:32,  5.15it/s]

RAG:  68%|██████▊   | 999/1475 [02:34<01:17,  6.15it/s]

RAG:  68%|██████▊   | 1000/1475 [02:34<01:19,  5.98it/s]

RAG:  68%|██████▊   | 1001/1475 [02:35<01:14,  6.39it/s]

Checkpoint: 1000/1475

RAG:  68%|██████▊   | 1002/1475 [02:35<01:09,  6.80it/s]

RAG:  68%|██████▊   | 1003/1475 [02:35<01:06,  7.09it/s]

RAG:  68%|██████▊   | 1004/1475 [02:35<01:02,  7.56it/s]

RAG:  68%|██████▊   | 1005/1475 [02:35<01:08,  6.83it/s]

RAG:  68%|██████▊   | 1007/1475 [02:35<01:14,  6.31it/s]

RAG:  68%|██████▊   | 1008/1475 [02:36<01:15,  6.22it/s]

RAG:  68%|██████▊   | 1010/1475 [02:36<01:07,  6.91it/s]

RAG:  69%|██████▊   | 1013/1475 [02:36<01:08,  6.70it/s]

RAG:  69%|██████▊   | 1014/1475 [02:37<01:17,  5.97it/s]

RAG:  69%|██████▉   | 1015/1475 [02:37<01:21,  5.61it/s]

RAG:  69%|██████▉   | 1016/1475 [02:37<01:14,  6.13it/s]

RAG:  69%|██████▉   | 1018/1475 [02:37<01:02,  7.28it/s]

RAG:  69%|██████▉   | 1019/1475 [02:37<01:07,  6.77it/s]

RAG:  69%|██████▉   | 1020/1475 [02:37<01:02,  7.25it/s]

RAG:  69%|██████▉   | 1021/1475 [02:38<01:06,  6.82it/s]

RAG:  69%|██████▉   | 1023/1475 [02:38<01:22,  5.47it/s]

RAG:  69%|██████▉   | 1024/1475 [02:38<01:20,  5.60it/s]

RAG:  69%|██████▉   | 1025/1475 [02:38<01:16,  5.90it/s]

Checkpoint: 1025/1475

RAG:  70%|██████▉   | 1028/1475 [02:39<00:58,  7.61it/s]

RAG:  70%|██████▉   | 1029/1475 [02:39<00:56,  7.86it/s]

RAG:  70%|██████▉   | 1030/1475 [02:39<01:12,  6.10it/s]

RAG:  70%|██████▉   | 1031/1475 [02:39<01:29,  4.96it/s]

RAG:  70%|███████   | 1034/1475 [02:40<01:00,  7.31it/s]

RAG:  70%|███████   | 1035/1475 [02:40<01:34,  4.67it/s]

RAG:  70%|███████   | 1036/1475 [02:40<01:43,  4.22it/s]

RAG:  70%|███████   | 1038/1475 [02:41<01:19,  5.50it/s]

RAG:  70%|███████   | 1039/1475 [02:41<01:13,  5.95it/s]

RAG:  71%|███████   | 1041/1475 [02:41<01:15,  5.73it/s]

RAG:  71%|███████   | 1042/1475 [02:41<01:30,  4.79it/s]

RAG:  71%|███████   | 1043/1475 [02:42<01:20,  5.37it/s]

RAG:  71%|███████   | 1045/1475 [02:42<01:10,  6.06it/s]

RAG:  71%|███████   | 1047/1475 [02:42<01:02,  6.82it/s]

RAG:  71%|███████   | 1048/1475 [02:42<01:27,  4.89it/s]

RAG:  71%|███████   | 1049/1475 [02:43<01:40,  4.23it/s]

RAG:  71%|███████   | 1050/1475 [02:43<01:55,  3.69it/s]

RAG:  71%|███████▏  | 1052/1475 [02:43<01:20,  5.23it/s]

Checkpoint: 1050/1475

RAG:  71%|███████▏  | 1053/1475 [02:43<01:15,  5.60it/s]

RAG:  71%|███████▏  | 1054/1475 [02:44<01:26,  4.84it/s]

RAG:  72%|███████▏  | 1055/1475 [02:44<01:44,  4.01it/s]

RAG:  72%|███████▏  | 1057/1475 [02:44<01:19,  5.23it/s]

RAG:  72%|███████▏  | 1060/1475 [02:45<01:06,  6.27it/s]

RAG:  72%|███████▏  | 1061/1475 [02:45<01:15,  5.45it/s]

RAG:  72%|███████▏  | 1063/1475 [02:45<00:58,  7.08it/s]

RAG:  72%|███████▏  | 1064/1475 [02:46<01:14,  5.52it/s]

RAG:  72%|███████▏  | 1066/1475 [02:46<01:01,  6.66it/s]

RAG:  72%|███████▏  | 1067/1475 [02:46<01:11,  5.69it/s]

RAG:  72%|███████▏  | 1068/1475 [02:46<01:26,  4.71it/s]

RAG:  73%|███████▎  | 1070/1475 [02:47<01:12,  5.58it/s]

RAG:  73%|███████▎  | 1072/1475 [02:47<01:39,  4.07it/s]

RAG:  73%|███████▎  | 1075/1475 [02:48<01:09,  5.74it/s]

RAG:  73%|███████▎  | 1077/1475 [02:48<00:57,  6.87it/s]

Checkpoint: 1075/1475

RAG:  73%|███████▎  | 1078/1475 [02:48<01:10,  5.59it/s]

RAG:  73%|███████▎  | 1079/1475 [02:48<01:16,  5.19it/s]

RAG:  73%|███████▎  | 1080/1475 [02:48<01:09,  5.66it/s]

RAG:  73%|███████▎  | 1081/1475 [02:49<01:15,  5.24it/s]

RAG:  73%|███████▎  | 1082/1475 [02:49<01:14,  5.27it/s]

RAG:  73%|███████▎  | 1084/1475 [02:49<01:02,  6.27it/s]

RAG:  74%|███████▎  | 1085/1475 [02:49<01:23,  4.70it/s]

RAG:  74%|███████▍  | 1088/1475 [02:50<00:56,  6.85it/s]

RAG:  74%|███████▍  | 1090/1475 [02:50<01:02,  6.15it/s]

RAG:  74%|███████▍  | 1092/1475 [02:50<00:49,  7.80it/s]

RAG:  74%|███████▍  | 1094/1475 [02:51<01:21,  4.65it/s]

RAG:  74%|███████▍  | 1096/1475 [02:51<01:16,  4.94it/s]

RAG:  74%|███████▍  | 1097/1475 [02:52<01:21,  4.66it/s]

RAG:  75%|███████▍  | 1100/1475 [02:52<01:00,  6.24it/s]

Checkpoint: 1100/1475

RAG:  75%|███████▍  | 1102/1475 [02:52<00:58,  6.34it/s]

RAG:  75%|███████▍  | 1103/1475 [02:52<00:59,  6.21it/s]

RAG:  75%|███████▍  | 1104/1475 [02:53<00:57,  6.42it/s]

RAG:  75%|███████▍  | 1105/1475 [02:53<01:01,  6.00it/s]

RAG:  75%|███████▍  | 1106/1475 [02:53<00:59,  6.25it/s]

RAG:  75%|███████▌  | 1107/1475 [02:53<01:00,  6.04it/s]

RAG:  75%|███████▌  | 1108/1475 [02:53<01:02,  5.89it/s]

RAG:  75%|███████▌  | 1109/1475 [02:54<01:26,  4.21it/s]

RAG:  75%|███████▌  | 1111/1475 [02:54<01:00,  5.98it/s]

RAG:  75%|███████▌  | 1112/1475 [02:54<01:14,  4.86it/s]

RAG:  75%|███████▌  | 1113/1475 [02:54<01:07,  5.37it/s]

RAG:  76%|███████▌  | 1114/1475 [02:54<01:04,  5.59it/s]

RAG:  76%|███████▌  | 1115/1475 [02:55<01:09,  5.19it/s]

RAG:  76%|███████▌  | 1116/1475 [02:55<01:14,  4.81it/s]

RAG:  76%|███████▌  | 1119/1475 [02:55<01:05,  5.45it/s]

RAG:  76%|███████▌  | 1121/1475 [02:56<00:58,  6.08it/s]

RAG:  76%|███████▌  | 1122/1475 [02:56<00:54,  6.47it/s]

RAG:  76%|███████▌  | 1123/1475 [02:56<01:15,  4.66it/s]

RAG:  76%|███████▋  | 1125/1475 [02:57<01:18,  4.46it/s]

Checkpoint: 1125/1475

RAG:  77%|███████▋  | 1130/1475 [02:57<00:56,  6.15it/s]

RAG:  77%|███████▋  | 1131/1475 [02:58<01:09,  4.94it/s]

RAG:  77%|███████▋  | 1132/1475 [02:58<01:16,  4.49it/s]

RAG:  77%|███████▋  | 1135/1475 [02:58<00:53,  6.36it/s]

RAG:  77%|███████▋  | 1136/1475 [02:58<00:50,  6.69it/s]

RAG:  77%|███████▋  | 1137/1475 [02:59<01:09,  4.86it/s]

RAG:  77%|███████▋  | 1138/1475 [02:59<01:07,  5.01it/s]

RAG:  77%|███████▋  | 1139/1475 [02:59<01:02,  5.35it/s]

RAG:  77%|███████▋  | 1140/1475 [02:59<00:55,  6.00it/s]

RAG:  77%|███████▋  | 1141/1475 [02:59<00:51,  6.46it/s]

RAG:  77%|███████▋  | 1142/1475 [02:59<00:46,  7.09it/s]

RAG:  78%|███████▊  | 1144/1475 [03:00<00:35,  9.20it/s]

RAG:  78%|███████▊  | 1146/1475 [03:00<01:08,  4.77it/s]

RAG:  78%|███████▊  | 1147/1475 [03:00<01:04,  5.05it/s]

RAG:  78%|███████▊  | 1149/1475 [03:01<00:56,  5.72it/s]

RAG:  78%|███████▊  | 1150/1475 [03:01<00:53,  6.07it/s]

Checkpoint: 1150/1475

RAG:  78%|███████▊  | 1152/1475 [03:01<01:02,  5.19it/s]

RAG:  78%|███████▊  | 1154/1475 [03:02<00:50,  6.39it/s]

RAG:  78%|███████▊  | 1155/1475 [03:02<00:51,  6.25it/s]

RAG:  78%|███████▊  | 1156/1475 [03:02<01:02,  5.10it/s]

RAG:  78%|███████▊  | 1157/1475 [03:02<01:08,  4.64it/s]

RAG:  79%|███████▊  | 1159/1475 [03:03<00:55,  5.70it/s]

RAG:  79%|███████▉  | 1162/1475 [03:03<00:53,  5.89it/s]

RAG:  79%|███████▉  | 1163/1475 [03:03<00:51,  6.10it/s]

RAG:  79%|███████▉  | 1164/1475 [03:04<01:20,  3.84it/s]

RAG:  79%|███████▉  | 1165/1475 [03:04<01:10,  4.40it/s]

RAG:  79%|███████▉  | 1168/1475 [03:04<00:53,  5.72it/s]

RAG:  79%|███████▉  | 1169/1475 [03:04<00:49,  6.13it/s]

RAG:  79%|███████▉  | 1170/1475 [03:05<01:14,  4.12it/s]

RAG:  79%|███████▉  | 1172/1475 [03:05<00:54,  5.54it/s]

RAG:  80%|███████▉  | 1174/1475 [03:05<00:48,  6.23it/s]

RAG:  80%|███████▉  | 1175/1475 [03:06<00:53,  5.56it/s]

Checkpoint: 1175/1475

RAG:  80%|███████▉  | 1176/1475 [03:06<00:59,  5.00it/s]

RAG:  80%|███████▉  | 1177/1475 [03:06<01:00,  4.96it/s]

RAG:  80%|████████  | 1180/1475 [03:06<00:40,  7.37it/s]

RAG:  80%|████████  | 1181/1475 [03:07<00:48,  6.08it/s]

RAG:  80%|████████  | 1182/1475 [03:07<00:53,  5.53it/s]

RAG:  80%|████████  | 1183/1475 [03:07<00:59,  4.94it/s]

RAG:  80%|████████  | 1184/1475 [03:07<00:54,  5.31it/s]

RAG:  80%|████████  | 1186/1475 [03:07<00:38,  7.48it/s]

RAG:  81%|████████  | 1188/1475 [03:08<00:40,  7.11it/s]

RAG:  81%|████████  | 1189/1475 [03:08<00:40,  7.10it/s]

RAG:  81%|████████  | 1190/1475 [03:08<00:56,  5.06it/s]

RAG:  81%|████████  | 1191/1475 [03:08<00:49,  5.69it/s]

RAG:  81%|████████  | 1194/1475 [03:08<00:31,  8.79it/s]

RAG:  81%|████████  | 1196/1475 [03:09<00:32,  8.54it/s]

RAG:  81%|████████  | 1197/1475 [03:09<00:54,  5.12it/s]

RAG:  81%|████████  | 1198/1475 [03:10<01:03,  4.34it/s]

RAG:  81%|████████▏ | 1200/1475 [03:10<00:50,  5.46it/s]

Checkpoint: 1200/1475

RAG:  81%|████████▏ | 1202/1475 [03:10<00:51,  5.28it/s]

RAG:  82%|████████▏ | 1205/1475 [03:10<00:37,  7.14it/s]

RAG:  82%|████████▏ | 1206/1475 [03:11<00:40,  6.65it/s]

RAG:  82%|████████▏ | 1207/1475 [03:11<00:45,  5.88it/s]

RAG:  82%|████████▏ | 1209/1475 [03:11<00:38,  6.88it/s]

RAG:  82%|████████▏ | 1210/1475 [03:11<00:54,  4.86it/s]

RAG:  82%|████████▏ | 1213/1475 [03:12<00:36,  7.17it/s]

RAG:  82%|████████▏ | 1215/1475 [03:12<00:41,  6.31it/s]

RAG:  82%|████████▏ | 1216/1475 [03:12<00:38,  6.68it/s]

RAG:  83%|████████▎ | 1219/1475 [03:12<00:30,  8.39it/s]

RAG:  83%|████████▎ | 1220/1475 [03:13<00:36,  6.96it/s]

RAG:  83%|████████▎ | 1222/1475 [03:13<00:31,  8.13it/s]

RAG:  83%|████████▎ | 1224/1475 [03:13<00:35,  7.10it/s]

RAG:  83%|████████▎ | 1225/1475 [03:14<00:44,  5.56it/s]

Checkpoint: 1225/1475

RAG:  83%|████████▎ | 1228/1475 [03:14<00:34,  7.24it/s]

RAG:  83%|████████▎ | 1229/1475 [03:14<00:39,  6.16it/s]

RAG:  83%|████████▎ | 1230/1475 [03:14<00:37,  6.57it/s]

RAG:  84%|████████▎ | 1232/1475 [03:14<00:36,  6.74it/s]

RAG:  84%|████████▎ | 1233/1475 [03:15<00:38,  6.23it/s]

RAG:  84%|████████▍ | 1237/1475 [03:15<00:37,  6.39it/s]

RAG:  84%|████████▍ | 1238/1475 [03:15<00:37,  6.25it/s]

RAG:  84%|████████▍ | 1240/1475 [03:16<00:33,  7.01it/s]

RAG:  84%|████████▍ | 1242/1475 [03:16<00:36,  6.32it/s]

RAG:  84%|████████▍ | 1245/1475 [03:16<00:26,  8.52it/s]

RAG:  84%|████████▍ | 1246/1475 [03:17<00:43,  5.21it/s]

RAG:  85%|████████▍ | 1247/1475 [03:17<00:42,  5.33it/s]

RAG:  85%|████████▍ | 1248/1475 [03:17<00:44,  5.14it/s]

RAG:  85%|████████▍ | 1250/1475 [03:17<00:39,  5.75it/s]

RAG:  85%|████████▍ | 1251/1475 [03:18<00:38,  5.79it/s]

Checkpoint: 1250/1475

RAG:  85%|████████▍ | 1253/1475 [03:18<00:32,  6.75it/s]

RAG:  85%|████████▌ | 1255/1475 [03:18<00:32,  6.82it/s]

RAG:  85%|████████▌ | 1256/1475 [03:18<00:38,  5.73it/s]

RAG:  85%|████████▌ | 1257/1475 [03:19<00:35,  6.17it/s]

RAG:  85%|████████▌ | 1258/1475 [03:19<00:33,  6.51it/s]

RAG:  85%|████████▌ | 1260/1475 [03:19<00:44,  4.81it/s]

RAG:  85%|████████▌ | 1261/1475 [03:19<00:41,  5.22it/s]

RAG:  86%|████████▌ | 1266/1475 [03:20<00:25,  8.26it/s]

RAG:  86%|████████▌ | 1267/1475 [03:20<00:36,  5.74it/s]

RAG:  86%|████████▌ | 1268/1475 [03:20<00:34,  5.94it/s]

RAG:  86%|████████▌ | 1269/1475 [03:21<00:37,  5.52it/s]

RAG:  86%|████████▌ | 1270/1475 [03:21<00:35,  5.73it/s]

RAG:  86%|████████▋ | 1274/1475 [03:21<00:21,  9.30it/s]

RAG:  86%|████████▋ | 1275/1475 [03:21<00:27,  7.27it/s]

Checkpoint: 1275/1475

RAG:  87%|████████▋ | 1276/1475 [03:22<00:42,  4.63it/s]

RAG:  87%|████████▋ | 1278/1475 [03:22<00:32,  6.06it/s]

RAG:  87%|████████▋ | 1280/1475 [03:22<00:25,  7.52it/s]

RAG:  87%|████████▋ | 1283/1475 [03:23<00:26,  7.14it/s]

RAG:  87%|████████▋ | 1284/1475 [03:23<00:27,  6.93it/s]

RAG:  87%|████████▋ | 1285/1475 [03:23<00:25,  7.34it/s]

RAG:  87%|████████▋ | 1286/1475 [03:23<00:25,  7.55it/s]

RAG:  87%|████████▋ | 1287/1475 [03:23<00:29,  6.43it/s]

RAG:  87%|████████▋ | 1289/1475 [03:23<00:23,  7.89it/s]

RAG:  87%|████████▋ | 1290/1475 [03:24<00:31,  5.91it/s]

RAG:  88%|████████▊ | 1291/1475 [03:24<00:33,  5.52it/s]

RAG:  88%|████████▊ | 1293/1475 [03:24<00:26,  6.96it/s]

RAG:  88%|████████▊ | 1295/1475 [03:24<00:22,  8.13it/s]

RAG:  88%|████████▊ | 1296/1475 [03:24<00:22,  7.81it/s]

RAG:  88%|████████▊ | 1298/1475 [03:25<00:21,  8.22it/s]

RAG:  88%|████████▊ | 1300/1475 [03:25<00:26,  6.68it/s]

Checkpoint: 1300/1475

RAG:  88%|████████▊ | 1301/1475 [03:25<00:29,  5.91it/s]

RAG:  88%|████████▊ | 1304/1475 [03:26<00:21,  7.94it/s]

RAG:  89%|████████▊ | 1306/1475 [03:26<00:25,  6.50it/s]

RAG:  89%|████████▊ | 1307/1475 [03:26<00:27,  6.02it/s]

RAG:  89%|████████▊ | 1308/1475 [03:26<00:27,  6.02it/s]

RAG:  89%|████████▉ | 1311/1475 [03:26<00:17,  9.31it/s]

RAG:  89%|████████▉ | 1313/1475 [03:27<00:15, 10.74it/s]

RAG:  89%|████████▉ | 1315/1475 [03:27<00:20,  7.78it/s]

RAG:  89%|████████▉ | 1317/1475 [03:27<00:24,  6.44it/s]

RAG:  89%|████████▉ | 1319/1475 [03:28<00:27,  5.64it/s]

RAG:  90%|████████▉ | 1321/1475 [03:28<00:21,  7.04it/s]

RAG:  90%|████████▉ | 1323/1475 [03:28<00:18,  8.15it/s]

RAG:  90%|████████▉ | 1325/1475 [03:29<00:20,  7.16it/s]

Checkpoint: 1325/1475

RAG:  90%|████████▉ | 1326/1475 [03:29<00:23,  6.24it/s]

RAG:  90%|████████▉ | 1327/1475 [03:29<00:22,  6.62it/s]

RAG:  90%|█████████ | 1328/1475 [03:29<00:22,  6.49it/s]

RAG:  90%|█████████ | 1329/1475 [03:29<00:30,  4.85it/s]

RAG:  90%|█████████ | 1330/1475 [03:30<00:29,  4.87it/s]

RAG:  90%|█████████ | 1332/1475 [03:30<00:19,  7.16it/s]

RAG:  90%|█████████ | 1334/1475 [03:30<00:18,  7.79it/s]

RAG:  91%|█████████ | 1335/1475 [03:30<00:17,  7.81it/s]

RAG:  91%|█████████ | 1336/1475 [03:30<00:22,  6.19it/s]

RAG:  91%|█████████ | 1338/1475 [03:30<00:16,  8.17it/s]

RAG:  91%|█████████ | 1340/1475 [03:31<00:20,  6.58it/s]

RAG:  91%|█████████ | 1342/1475 [03:31<00:15,  8.31it/s]

RAG:  91%|█████████ | 1344/1475 [03:32<00:22,  5.82it/s]

RAG:  91%|█████████ | 1345/1475 [03:32<00:22,  5.88it/s]

RAG:  91%|█████████▏| 1346/1475 [03:32<00:21,  6.07it/s]

RAG:  91%|█████████▏| 1348/1475 [03:32<00:20,  6.20it/s]

RAG:  91%|█████████▏| 1349/1475 [03:32<00:20,  6.18it/s]

RAG:  92%|█████████▏| 1350/1475 [03:33<00:22,  5.64it/s]

Checkpoint: 1350/1475

RAG:  92%|█████████▏| 1353/1475 [03:33<00:24,  5.08it/s]

RAG:  92%|█████████▏| 1355/1475 [03:33<00:19,  6.31it/s]

RAG:  92%|█████████▏| 1357/1475 [03:34<00:16,  7.34it/s]

RAG:  92%|█████████▏| 1359/1475 [03:34<00:13,  8.81it/s]

RAG:  92%|█████████▏| 1361/1475 [03:34<00:22,  5.03it/s]

RAG:  92%|█████████▏| 1362/1475 [03:35<00:21,  5.19it/s]

RAG:  92%|█████████▏| 1364/1475 [03:35<00:16,  6.61it/s]

RAG:  93%|█████████▎| 1368/1475 [03:35<00:14,  7.20it/s]

RAG:  93%|█████████▎| 1369/1475 [03:35<00:15,  6.79it/s]

RAG:  93%|█████████▎| 1370/1475 [03:36<00:17,  6.17it/s]

RAG:  93%|█████████▎| 1373/1475 [03:36<00:11,  9.15it/s]

RAG:  93%|█████████▎| 1375/1475 [03:36<00:12,  7.77it/s]

Checkpoint: 1375/1475

RAG:  93%|█████████▎| 1377/1475 [03:37<00:14,  6.93it/s]

RAG:  93%|█████████▎| 1378/1475 [03:37<00:15,  6.41it/s]

RAG:  94%|█████████▎| 1380/1475 [03:37<00:12,  7.54it/s]

RAG:  94%|█████████▎| 1382/1475 [03:37<00:13,  6.72it/s]

RAG:  94%|█████████▍| 1385/1475 [03:38<00:11,  7.66it/s]

RAG:  94%|█████████▍| 1386/1475 [03:38<00:12,  7.14it/s]

RAG:  94%|█████████▍| 1389/1475 [03:38<00:10,  8.54it/s]

RAG:  94%|█████████▍| 1390/1475 [03:39<00:15,  5.49it/s]

RAG:  94%|█████████▍| 1392/1475 [03:39<00:11,  7.01it/s]

RAG:  94%|█████████▍| 1393/1475 [03:39<00:12,  6.60it/s]

RAG:  95%|█████████▍| 1394/1475 [03:39<00:12,  6.67it/s]

RAG:  95%|█████████▍| 1396/1475 [03:39<00:09,  8.45it/s]

RAG:  95%|█████████▍| 1398/1475 [03:39<00:09,  8.12it/s]

RAG:  95%|█████████▍| 1399/1475 [03:40<00:09,  8.13it/s]

RAG:  95%|█████████▍| 1400/1475 [03:40<00:12,  6.18it/s]

Checkpoint: 1400/1475

RAG:  95%|█████████▌| 1403/1475 [03:40<00:10,  7.10it/s]

RAG:  95%|█████████▌| 1404/1475 [03:41<00:13,  5.14it/s]

RAG:  95%|█████████▌| 1406/1475 [03:41<00:13,  4.97it/s]

RAG:  96%|█████████▌| 1409/1475 [03:41<00:09,  7.16it/s]

RAG:  96%|█████████▌| 1411/1475 [03:41<00:07,  8.21it/s]

RAG:  96%|█████████▌| 1413/1475 [03:42<00:11,  5.18it/s]

RAG:  96%|█████████▌| 1417/1475 [03:42<00:08,  6.65it/s]

RAG:  96%|█████████▌| 1419/1475 [03:43<00:07,  7.63it/s]

RAG:  96%|█████████▋| 1421/1475 [03:43<00:08,  6.01it/s]

RAG:  96%|█████████▋| 1422/1475 [03:44<00:11,  4.54it/s]

RAG:  97%|█████████▋| 1425/1475 [03:44<00:07,  6.32it/s]

RAG:  97%|█████████▋| 1427/1475 [03:44<00:06,  7.49it/s]

Checkpoint: 1425/1475

RAG:  97%|█████████▋| 1429/1475 [03:45<00:09,  5.09it/s]

RAG:  97%|█████████▋| 1431/1475 [03:45<00:07,  6.23it/s]

RAG:  97%|█████████▋| 1433/1475 [03:45<00:05,  7.52it/s]

RAG:  97%|█████████▋| 1435/1475 [03:45<00:04,  8.34it/s]

RAG:  97%|█████████▋| 1437/1475 [03:46<00:06,  5.72it/s]

RAG:  97%|█████████▋| 1438/1475 [03:46<00:07,  4.68it/s]

RAG:  98%|█████████▊| 1440/1475 [03:47<00:09,  3.69it/s]

RAG:  98%|█████████▊| 1442/1475 [03:47<00:07,  4.67it/s]

RAG:  98%|█████████▊| 1445/1475 [03:47<00:04,  6.46it/s]

RAG:  98%|█████████▊| 1446/1475 [03:47<00:04,  6.41it/s]

RAG:  98%|█████████▊| 1447/1475 [03:48<00:07,  3.69it/s]

RAG:  98%|█████████▊| 1450/1475 [03:48<00:04,  5.55it/s]

Checkpoint: 1450/1475

RAG:  98%|█████████▊| 1452/1475 [03:49<00:04,  5.37it/s]

RAG:  99%|█████████▊| 1454/1475 [03:49<00:03,  6.48it/s]

RAG:  99%|█████████▊| 1456/1475 [03:49<00:03,  5.94it/s]

RAG:  99%|█████████▉| 1457/1475 [03:50<00:02,  6.24it/s]

RAG:  99%|█████████▉| 1459/1475 [03:50<00:02,  6.69it/s]

RAG:  99%|█████████▉| 1461/1475 [03:50<00:01,  8.12it/s]

RAG:  99%|█████████▉| 1463/1475 [03:50<00:01,  7.62it/s]

RAG:  99%|█████████▉| 1465/1475 [03:50<00:01,  8.07it/s]

RAG:  99%|█████████▉| 1466/1475 [03:51<00:01,  8.33it/s]

RAG:  99%|█████████▉| 1467/1475 [03:51<00:01,  6.22it/s]

RAG: 100%|█████████▉| 1468/1475 [03:51<00:01,  6.36it/s]

RAG: 100%|█████████▉| 1470/1475 [03:51<00:00,  7.42it/s]

RAG: 100%|█████████▉| 1471/1475 [03:52<00:00,  5.67it/s]

RAG: 100%|█████████▉| 1473/1475 [03:52<00:00,  7.53it/s]

RAG: 100%|██████████| 1475/1475 [03:53<00:00,  3.66it/s]

RAG: 100%|██████████| 1475/1475 [03:53<00:00,  6.32it/s]

Checkpoint: 1475/1475
Saved 1500 results to /Users/veniamin/Projects/chatbot-evals-ai/data/synthetic_revolut_rag_outputs.csv
Total results: 1500

,persona,scenario,modifier,query,answer,extracted_context,retrieved_articles
0,eu_freelancer_traveling_uae_male_29,fraud_unrecognised_card_payment,poor_internet_connection,noticed a suspicious card payment from yesterd...,If you noticed a suspicious card payment that ...,[Article 1] My card payment was declined by th...,My card payment was declined by the security s...
1,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,angry_after_waiting,JUST SAW ATM withdrawal I DIDN'T MAKE! Need th...,To report a fraudulent ATM withdrawal you didn...,[Article 1] Why is my ATM withdrawal pending?\...,Why is my ATM withdrawal pending? | My card ha...
2,eu_freelancer_traveling_uae_male_29,fraud_unrecognised_card_payment,empty,I saw a card payment I don't recognize. How ca...,To report a card payment you don't recognize a...,[Article 1] Report a card payment as a scam or...,Report a card payment as a scam or fraud | My ...
3,eu_freelancer_traveling_uae_male_29,fraud_unrecognised_card_payment,calm_at_home,I noticed an unexpected charge on my Revolut a...,To report an unexpected charge on your Revolut...,[Article 1] Report a fraudulent ATM withdrawal...,Report a fraudulent ATM withdrawal | Report a ...
4,eu_freelancer_traveling_uae_male_29,fraud_unauthorised_atm_withdrawal,vague_first_message,unexpected atm withdrawal in dubai just now bu...,To report an unexpected ATM withdrawal that wa...,[Article 1] Report a fraudulent ATM withdrawal...,Report a fraudulent ATM withdrawal | My card h...

In [10]:
# Gate G4 - Verify RAG outputs
print("="*60)
print("Gate G4 - RAG Output Validation")
print("="*60)

df_final = pd.read_csv(RAG_OUTPUT_PATH)

# Row count
print(f"Row count: {len(df_final)} (expected: 1500)")

# Columns
expected_cols = ["persona", "scenario", "modifier", "query", "answer", "extracted_context", "retrieved_articles"]
print(f"Columns correct: {list(df_final.columns) == expected_cols}")

# Null checks
null_answers = df_final["answer"].isnull().sum()
null_context = df_final["extracted_context"].isnull().sum()
print(f"Null answers: {null_answers}")
print(f"Null context: {null_context}")

# Retrieved articles
empty_retrieved = (df_final["retrieved_articles"].str.len() == 0).sum()
print(f"Empty retrieved_articles: {empty_retrieved} ({empty_retrieved/len(df_final)*100:.1f}%)")

# Sample outputs
print(f"\nSample rows:")
for i, row in df_final.sample(3).iterrows():
    print(f"\n[{row['modifier'][:15]:15}] Query: {row['query'][:60]}...")
    print(f"Answer: {row['answer'][:80]}...")
    print(f"Retrieved: {row['retrieved_articles'][:100]}...")

# Final verdict
g4_pass = (len(df_final) == 1500 and 
           list(df_final.columns) == expected_cols and
           null_answers == 0 and 
           empty_retrieved / len(df_final) <= 0.01)

print(f"\n{'✅ Gate G4 PASSED' if g4_pass else '❌ Gate G4 FAILED'}")

============================================================
Gate G4 - RAG Output Validation
============================================================

Row count: 1500 (expected: 1500)
Columns correct: True
Null answers: 0
Null context: 0
Empty retrieved_articles: 0 (0.0%)

Sample rows:

[panic_security_] Query: Revolut Terminal not processing payments! Customers waiting ...
Answer: Based on the provided help articles, the issue with the Revolut Terminal not pro...
Retrieved: Failed payments on the Revolut Terminal | I'm having trouble using my Revolut Terminal | Cards and c...

[confused_by_app] Query: I want to move CHF to EUR with schedule, but don't see fee i...
Answer: You can find information about fees for international transfers, including CHF t...
Retrieved: Schedule a transfer | Why was my transfer sent via an intermediary bank? | Bank transfer fees | Mana...

[rushing_with_ty] Query: how is interest added on savings is it taxed like what rates...
Answer: To understand how interest is added on savings, whether it is taxed, and what ra...
Retrieved: Earning interest with Savings | Tax on Savings | How to calculate interest on Savings accounts | How...

✅ Gate G4 PASSED

## Milestone 0 Verification

Verify .gitignore excludes .env but not data CSVs:

In [11]:
# Check .gitignore status
gitignore_path = Path(os.getcwd()).parent.parent / ".gitignore"
with open(gitignore_path) as f:
    gitignore = f.read()
print(".env in .gitignore:", ".env" in gitignore)
print("data/*.csv in .gitignore:", "data/*.csv" in gitignore)
print("First 20 lines of .gitignore:")
print('\n'.join(gitignore.split('\n')[:20]))

.env in .gitignore: True
data/*.csv in .gitignore: False
First 20 lines of .gitignore:
node_modules
.next
out
dist
.env*
.DS_Store
*.log
*.sqlite
coverage

# local archives
*.zip
*.tar.gz